# Generated by Django 5.2.14 on 2026-05-09 13:56

import apps.identity.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("oauth_providers", models.JSONField(blank=True, default=list)),
                ("display_name", models.CharField(max_length=200)),
                ("locale", models.CharField(default="it-IT", max_length=10)),
                ("timezone", models.CharField(default="Europe/Rome", max_length=50)),
                ("notification_preferences", models.JSONField(blank=True, default=dict)),
                (
                    "privacy_preset",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("balanced", "Balanced"),
                            ("open", "Open"),
                            ("custom", "Custom"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("privacy_custom_overrides", models.JSONField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "identity_users",
            },
            managers=[
                ("objects", apps.identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("given_names", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("surname_at_birth", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nicknames",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_living", models.BooleanField()),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "birth_date_precision",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("decade", "Decade"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("birth_place", models.CharField(blank=True, max_length=255, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                (
                    "death_date_precision",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("decade", "Decade"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("death_place", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("unknown", "Unknown"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("profile_photo_content_id", models.UUIDField(blank=True, null=True)),
                ("short_bio", models.TextField(blank=True, null=True)),
                ("is_claimed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_persons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "persons",
                "db_table": "identity_persons",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invited_email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "inviter_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "db_table": "identity_invitations",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_account",
                to="identity.person",
            ),
        ),
        migrations.CreateModel(
            name="PersonClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "claiming_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="identity.person",
                    ),
                ),
                (
                    "resolved_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person claim",
                "verbose_name_plural": "person claims",
                "db_table": "identity_person_claims",
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["surname", "given_names"], name="identity_pe_surname_7b1ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["is_living"], name="identity_pe_is_livi_e0fccc_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["archived_at"], name="identity_pe_archive_f90ba8_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["created_by_user"], name="identity_pe_created_4e55fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_living", True), ("death_date__isnull", False), _connector="OR"
                ),
                name="person_dead_must_have_death_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("birth_date__isnull", True),
                    ("death_date__isnull", True),
                    ("birth_date__lte", models.F("death_date")),
                    _connector="OR",
                ),
                name="person_birth_before_death",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["status"], name="identity_in_status_aacb08_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["invited_email"], name="identity_in_invited_3de1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["expires_at"], name="identity_in_expires_f614fd_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["deleted_at"], name="identity_us_deleted_af2631_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email_verified_at"], name="identity_us_email_v_e53b4f_idx"),
        ),
        migrations.AddIndex(
            model_name="personclaim",
            index=models.Index(fields=["status"], name="identity_pe_status_f69467_idx"),
        ),
        migrations.AddIndex(
            model_name="personclaim",
            index=models.Index(fields=["person", "status"], name="identity_pe_person__d9d939_idx"),
        ),
        migrations.AddConstraint(
            model_name="personclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("person", "claiming_user"),
                name="unique_pending_claim_per_person_user",
            ),
        ),
    ]
